Fixed search_data function issue in client.py script
fermisda/condb2 pull request #1
Opened 2024-03-04 16:52 UTC by AnaVizcaya

namedtuple typename does not accept string with . so using the folder name schema.tablename does not work in all cases. This should fix that

2024-03-04 20:15 UTC, vmp2575 requested changes
Ana Paula, please see the comments and adjust the code

2024-03-04 20:15 UTC, vmp2575 commented on condb/client.py
> +            folder1 = folder.split('.')[0]
As you are trying to extract the table name, it should be: 
`    folder1 = folder.split('.')[-1]`
This way it will work in both cases, with schema name and without it.

2024-03-04 20:15 UTC, vmp2575 commented on condb/client.py
> +            folder1 = folder.split('.')[0]
Same thing here

2024-03-05 21:44 UTC, AnaVizcaya commented on condb/client.py
> +            folder1 = folder.split('.')[0]
You are right, although it work, it's more correct to have there the table name and not the db schema

2024-03-05 21:44 UTC, AnaVizcaya commented on condb/client.py
> +            folder1 = folder.split('.')[0]
Yes

2024-03-05 21:57 UTC, vmp2575 commented
Looks good to me.

2024-03-05 21:57 UTC, merged